### ISSUE TITLE
HTMLParser failure during build

### ISSUE THREAD

**Issue by mariam-crissi** [mars/create-react-app-buildpack#68] opened 2017-09-06 09:30 UTC
i am trying to host the react app...(https://github.com/mariam-crissi/React-Updated-App).But it returns the following error..

    remote: -----> Caching build
    remote:        Clearing previous node cache
    remote:        Saving 2 cacheDirectories (default):
    remote:        - node_modules
    remote:        - bower_components (nothing to cache)
    remote: 
    remote: -----> Build succeeded!
    remote: =====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git
    remote: =====> Detected Framework: React.js (create-react-app)
    remote:        Writing `static.json` to support create-react-app
    remote:        Enabling runtime environment variables
    remote: 
    remote: > reactapp@0.1.0 build /tmp/build_42f259ce4f45494db0f34cb5e790d417
    remote: > react-scripts build
    remote: 
    remote: Creating an optimized production build...
    remote: Failed to compile.
    remote: 

    remote:   - htmlparser.js:235 new HTMLParser
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[html-minifier]/src/htmlparser.js:2    35:13
    remote:   
    remote:   - htmlminifier.js:946 minify
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[html-minifier]/src/htmlminifier.js    :946:3
    remote:   
    remote:   - htmlminifier.js:1299 exports.minify
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[html-minifier]/src/htmlminifier.js    :1299:10
    remote:   
    remote:   - index.js:296 
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[html-webpack-plugin]/index.js:296:    16
    remote:   
    remote:   - util.js:16 tryCatcher
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[bluebird]/js/release/util.js:16:23  
    remote:   - promise.js:512 Promise._settlePromiseFromHandler
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[bluebird]/js/release/promise.js:51    2:31
     remote:   
     remote:   - promise.js:569 Promise._settlePromise
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[bluebird]/js/release/promise.js:56    9:18
    remote:   
    remote:   - promise.js:614 Promise._settlePromise0
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[bluebird]/js/release/promise.js:61    4:10
    remote:   
    remote:   - promise.js:693 Promise._settlePromises
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[bluebird]/js/release/promise.js:69    3:18
    remote:   
    remote:   - async.js:133 Async._drainQueue
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[bluebird]/js/release/async.js:133:    16
    remote:   
    remote:   - async.js:143 Async._drainQueues
    remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[bluebird]/js/release/async.js:143:    10
     remote:   
    remote:   - async.js:17 Immediate.Async.drainQueues
     remote:     [build_42f259ce4f45494db0f34cb5e790d417]/[bluebird]/js/release/async.js:17:1    4
     remote: 
     remote: 
     remote: npm ERR! code ELIFECYCLE
     remote: npm ERR! errno 1
     remote: npm ERR! reactapp@0.1.0 build: `react-scripts build`
     remote: npm ERR! Exit status 1
     remote: npm ERR! 
     remote: npm ERR! Failed at the reactapp@0.1.0 build script.
     remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    remote: 
    remote: npm ERR! A complete log of this run can be found in:
    remote: npm ERR!     /app/.npm/_logs/2017-09-06T09_20_52_381Z-debug.log
     remote:  !     Push rejected, failed to compile React.js (create-react-app) multi app.
    remote: 
    remote:  !     Push failed
    remote: Verifying deploy...
    remote: 
    remote: !	Push rejected to test-react-google-map.
    remote: 
            To https://git.heroku.com/test-react-google-map.git
            ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'https://git.heroku.com/test-react-google-map.git'

**Comment by mars** [comment] 2017-09-06 17:05
Hi @mariam-crissi, looking at your [repo](https://github.com/mariam-crissi/React-Updated-App),

I see that the [`node_modules` directory is committed to git](https://github.com/mariam-crissi/React-Updated-App/tree/master/node_modules). I suspect that is the root cause. That directory should be removed from git & ignored. Otherwise, weird cross-platform build issues like this may occur. Heroku's Node buildpack will manage building & caching that for deployment.

Also, I found [dependencies in `package.json` include `babel-preset-stage-1`](https://github.com/mariam-crissi/React-Updated-App/blob/master/package.json#L7). I do not believe Babel presets should be added with `create-react-app` unless you've ejected the project.

**Comment by mariam-crissi** [comment] 2017-09-07 03:50
@mars   Thank you for your response...I will work on it by your updations  and let u know...

**Comment by mariam-crissi** [comment] 2017-09-07 05:05
Still facing the same issue

**Comment by mariam-crissi** [comment] 2017-09-07 05:32
Still facing the same issue

**Comment by mariam-crissi** [comment] 2017-09-07 06:53
-----> React.js (create-react-app) multi app detected

-----> Configure create-react-app build environment

       Using `NODE_ENV=development`

=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git

=====> Detected Framework: Multipack

=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git

=====> Detected Framework: Node.js

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NPM_CONFIG_PRODUCTION=false

       NODE_VERBOSE=false

       NODE_ENV=development

       NODE_MODULES_CACHE=true

-----> Installing binaries

       engines.node (package.json):  unspecified

       engines.npm (package.json):   unspecified (use default)

       

       Resolving node version 6.x...

       Downloading and installing node 6.11.3...

       Detected package-lock.json: defaulting npm to version 5.x.x

       Bootstrapping npm 5.x.x (replacing 3.10.10)...

       npm 5.4.1 installed

-----> Restoring cache

       Skipping cache restore (not-found)

-----> Building dependencies

       Installing node modules (package.json + package-lock)

       

       > uglifyjs-webpack-plugin@0.4.6 postinstall /tmp/build_4acd980d8a80e0486da141a82d0b3cee/node_modules/uglifyjs-webpack-plugin

       > node lib/post_install.js

       

       added 1285 packages in 46.326s

-----> Caching build

       Clearing previous node cache

       Saving 2 cacheDirectories (default):

       - node_modules

       - bower_components (nothing to cache)

-----> Build succeeded!

=====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git

=====> Detected Framework: React.js (create-react-app)

       Writing `static.json` to support create-react-app

       Enabling runtime environment variables

> landing@0.1.0 build /tmp/build_4acd980d8a80e0486da141a82d0b3cee

> react-scripts build

Creating an optimized production build...

Failed to compile.

DOCTYPE html>

  <html lang="en">

  <head>

            <meta charset="utf-8">

            <title>Sailor - Bootstrap 3 corporate template</title>

            <meta name="viewport" content="width=device-width, initial-scale=1.0  " />

            <meta name="description" content="Bootstrap 3 template for corporate   business" />

            

            <link href="./css/bootstrap.min.css" rel="stylesheet" /> 

            <link href="./css/cubeportfolio.min.css" rel="stylesheet" />

            <link href="./css/style.css" rel="stylesheet" />

            <link href="style/style.css" rel="stylesheet" />

            

            <link id="t-colors" href="./skins/default.css" rel="stylesheet" />

            

           

  </head>

  <body>

  <div id="wrapper">

       

       <header>

          <div class="navbar navbar-default navbar-static-top">

              <div class="container">

                  <div class="navbar-header">

                      <button type="button" class="navbar-toggle" data-toggle="c  ollapse" data-target=".navbar-collapse">

                          <span class="icon-bar"></span>

                          <span class="icon-bar"></span>

                          <span class="icon-bar"></span>

                      </button>

                      <a class="navbar-brand" href="#"><img src="./img/logo.png"   alt="" width="199" height="52" /></a>

                  </div>

                  <div class="navbar-collapse collapse ">

                      <ul class="nav navbar-nav">

                          <li>

                             <a href="#" class="dropdown-toggle " data-toggle="d  ropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Home</  a>

                                     

                          </li>

                          <li>

                              <a href="#" class="dropdown-toggle " data-toggle="  dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Featu  res</a>

                                   

                        </li>

                       <li><a href="#">Portfolio</a></li>

                       <li class="dropdown"><a href="#" class="dropdown-toggle "   data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others  ="false">Blog</a>

                                  

                      </li>

                      <li><a href="#">Contact</a></li>

                      </ul>

                  </div>

              </div>

          </div>

    </header>

    

  

    <section id="content">

    <div class="container">

    <div class="dat">

    <div class="row">

       <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">       <form role="form" class="register-form">

          <h2>Sign in <small>manage your account</small></h2>

          <hr class="colorgraph">

          <div class="form-group">

              <input type="email" name="email" id="email" class="form-control in  put-lg" placeholder="Email Address" tabindex="4">

          </div>

         <div class="form-group">

              <input type="password" class="form-control input-lg" id="exampleIn  putPassword1" placeholder="Password">

         </div>      

         <hr class="colorgraph">

         <div class="row">

           <div class="col-xs-12 col-md-6"><input type="submit" value="Sign in"   class="btn btn-primary btn-block btn-lg" tabindex="7"></div>       

         </div>

      </form>

    </div>

  </div>

  </div>

  </div>

  </section>

  <footer>

    

      <div class="container">

        <div class="row">

          <div class="col-lg-6">

            <div class="copyright">

              <p>&copy; Sailor Theme - All Right Reserved</p>

                          <div class="credits">

                              <a href="#">Business Bootstrap Themes</a> by <a hr  ef="#">BootstrapMade</a>

                          </div>

            </div>

          </div>

          <div class="col-lg-6">

            <ul class="social-network">

              <li><a href="#" data-placement="top" title="Facebook"><i class="fa   fa-facebook"></i></a></li>

              <li><a href="#" data-placement="top" title="Twitter"><i class="fa   fa-twitter"></i></a></li>

              <li><a href="#" data-placement="top" title="Linkedin"><i class="fa   fa-linkedin"></i></a></li>

              <li><a href="#" data-placement="top" title="Pinterest"><i class="f  a fa-pinterest"></i></a></li>

              <li><a href="#" data-placement="top" title="Google plus"><i class=  "fa fa-google-plus"></i></a></li>

            </ul>

          </div>

        </div>

      </div>

    

  </footer>

  </div>

  <a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>

  

  

  <script src="/bundle.js" type="text/javascript"></script>

  <script src="./js/jquery.min.js" type="text/javascript"></script>

  <script src="./js/modernizr.custom.js" type="text/javascript"></script>

  <script src="./js/bootstrap.min.js" type="text/javascript"></script>

  <script src="./js/jquery.appear.js" type="text/javascript"></script>

  <script src="./js/classie.js" type="text/javascript" ></script>

  <script src="./js/animate.js" type="text/javascript"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCg83y9n8X5LtVHE  J_HBtDS73mLrrPA5jQ" type="text/javascript" ></script>

  

  <script type="text/javascript" src="/static/js/main.bc11bf60.js"></script></bo  dy>

  </html>

  

  - htmlparser.js:235 new HTMLParser

    [build_4acd980d8a80e0486da141a82d0b3cee]/[html-minifier]/src/htmlparser.js:2    35:13

  

  - htmlminifier.js:946 minify

    [build_4acd980d8a80e0486da141a82d0b3cee]/[html-minifier]/src/htmlminifier.js    :946:3

  

  - htmlminifier.js:1299 exports.minify

    [build_4acd980d8a80e0486da141a82d0b3cee]/[html-minifier]/src/htmlminifier.js    :1299:10

  

  - index.js:296 

    [build_4acd980d8a80e0486da141a82d0b3cee]/[html-webpack-plugin]/index.js:296:    16

  

  - util.js:16 tryCatcher

    [build_4acd980d8a80e0486da141a82d0b3cee]/[bluebird]/js/release/util.js:16:23  

  - promise.js:512 Promise._settlePromiseFromHandler

    [build_4acd980d8a80e0486da141a82d0b3cee]/[bluebird]/js/release/promise.js:51    2:31

  

  - promise.js:569 Promise._settlePromise

    [build_4acd980d8a80e0486da141a82d0b3cee]/[bluebird]/js/release/promise.js:56    9:18

  

  - promise.js:614 Promise._settlePromise0

    [build_4acd980d8a80e0486da141a82d0b3cee]/[bluebird]/js/release/promise.js:61    4:10

  

  - promise.js:693 Promise._settlePromises

    [build_4acd980d8a80e0486da141a82d0b3cee]/[bluebird]/js/release/promise.js:69    3:18

  

  - async.js:133 Async._drainQueue

    [build_4acd980d8a80e0486da141a82d0b3cee]/[bluebird]/js/release/async.js:133:    16

  

  - async.js:143 Async._drainQueues

    [build_4acd980d8a80e0486da141a82d0b3cee]/[bluebird]/js/release/async.js:143:    10

  

  - async.js:17 Immediate.Async.drainQueues

    [build_4acd980d8a80e0486da141a82d0b3cee]/[bluebird]/js/release/async.js:17:1    4

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! landing@0.1.0 build: `react-scripts build`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the landing@0.1.0 build script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /app/.npm/_logs/2017-09-07T06_48_28_762Z-debug.log

 !     Push rejected, failed to compile React.js (create-react-app) multi app.

 !     Push failed

**Comment by mariam-crissi** [comment] 2017-09-07 06:54
This is the build log

**Comment by mariam-crissi** [comment] 2017-09-07 07:00
https://github.com/mariam-crissi/host-client.git    Link to the app I am trying to host

**Comment by mariam-crissi** [comment] 2017-09-07 08:32
https://stackoverflow.com/questions/46091569/issue-in-hosting-react-app-on-heroku 

I have added the build log in this stack exchange question..

**Comment by mars** [comment] 2017-09-07 19:18
I just cloned your repo and tried `npm install` + `npm run build`. I found that `npm run build` fails locally. So, this is an error with the code, not with Heroku deployment.

The failure is from `HTMLParser`, so I looked at the `public/index.html` and found a heavily customized template.

To check if that `public/index.html` content was the problem, I replaced it with the default HTML template code (see below). Then, `npm run build` completed successfully.

So, it seems **there is a problem with the validity of the HTML in your `public/index.html`** which breaks create-react-app's template engine. I suggest running it through an [HTML validator](https://validator.w3.org) to find problems, or manually breaking the template into smaller testable pieces until you find the part that causes the build error.


#### Default HTML template

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#000000">
    <!--
      manifest.json provides metadata used when your web app is added to the
      homescreen on Android. See https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/
    -->
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
    <!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.

      Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    -->
    <title>React App</title>
  </head>
  <body>
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <div id="root"></div>
    <!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm start` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    -->
  </body>
</html>
```

**Closed as completed** 2017-09-08 13:59 UTC
