### ISSUE TITLE
App not compatible with buildpack

### ISSUE THREAD

**Issue by Olivr3** [mars/create-react-app-buildpack#75] opened 2017-10-22 20:40 UTC
I am getting the following error when I try to "git push heroku master " for https://github.com/Olivr3/medtainer-web-app.git

```
Total 18 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://github.com/Olivr3/medtainer-web-app.git
remote:        bash: /app/tmp/buildpacks/4aff9c9b9fee4d728868386831b30486a015841813df934ebdbf6fc383177de9613880410c903937b3d8142711fda968e2248d0884e269145f937e69c6c7b0f0/bin/detect: No such file or directory
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to medtainer-app.
remote:
To https://git.heroku.com/medtainer-app.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/medtainer-app.git'
```
node version: v8.6.0

What Am I missing here?

**Comment by mars** [comment] 2017-10-23 03:35
That error means there is no `package.json` at the root of the git repo.

Either your app isn’t fully committed to git, or maybe it’s in a sub-directory? The React app must be at the top-level of the repo to work with this buildpack.

**Comment by mars** [comment] 2017-10-23 16:37
Just looked at the repo URL you posted in the title. It seems the repo is indeed empty. So, the buildpack doesn’t have an app to build.

**Comment by Olivr3** [comment] 2017-10-23 20:09
Hi @mars 

Thank you for your reply. 

You were right, the repository was empty. However, I am still getting the same error after committing the changes. 

I am trying to follow this simple guide without success. 

```
npm install -g create-react-app
create-react-app my-app
cd my-app
git init
heroku create -b https://github.com/mars/create-react-app-buildpack.git
git add .
git commit -m "react-create-app on Heroku"
git push heroku master
heroku open
```
How would you do to create a new react project and add it to Heroku?

Thx!

**Comment by mars** [comment] 2017-10-23 20:36
Those instructions are still good. So there's something else wrong with your code.

I just cloned your repo and tried to push to Heroku. Failed with the error:

```
remote: -----> Build failed
remote: 
remote:  !     Outdated Yarn lockfile
```

It seems you're using Yarn package manager, but it is in an inconsistent state. You'll need to solve this problem in order to deploy. If that's confusing, I'd suggest removing Yarn from the project; use npm instead:

```
git rm yarn.lock
git commit . -m 'Remove Yarn'
```

I just deployed your app successfully after removing Yarn.

**Closed as completed by mars** 2017-10-23 20:36 UTC

**Comment by Olivr3** [comment] 2017-10-23 20:48
@mars stop on! The problem was the yarn file for some reason. 

It is working now. Thx!

**Comment by SylarRuby** [comment] 2017-11-30 18:01
Yea, Im having this same issue. No yarn here

**Comment by mars** [comment] 2017-11-30 22:55
@SylarRuby, the reason this error **App not compatible with buildpack** appears is because `package.json` is missing or in the wrong place. Is your React app committed to git at the root of the repo?

**Comment by jayush07** [comment] 2017-12-27 13:51
i am facing the same problem with dot net application. 
Please help.

Do we need package.json in dot net too

**Comment by mars** [comment] 2017-12-29 17:07
@jayush07 looks like [Dot Net buildpack expects `project.json`](https://github.com/heroku/dotnet-buildpack/blob/master/bin/detect#L4). Probably filing an issue there makes more sense than this unrelated project.

**Comment by HazelHyeji** [comment] 2018-04-20 13:30
Hi @mars 
```
git rm yarn.lock
git commit . -m 'Remove Yarn'
```
 That worked for me. I spent lots of time solving this
```
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/fast-coast-44928.git'
```
Thank you so much!

**Comment by Shivendra30** [comment] 2018-12-06 14:23
Hi, I am having the following error

```
Enumerating objects: 5101, done.
Counting objects: 100% (5101/5101), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3690/3690), done.
Writing objects: 100% (5101/5101), 6.36 MiB | 52.00 KiB/s, done.
Total 5101 (delta 1117), reused 5081 (delta 1109)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
remote:
remote:  !     ERROR: Application not supported by 'heroku/nodejs' buildpack
remote:  !
remote:  !     The 'heroku/nodejs' buildpack is set on this application, but was
remote:  !     unable to detect a Node.js codebase.
remote:  !
remote:  !     A Node.js app on Heroku requires a 'package.json' at the root of
remote:  !     the directory structure.
remote:  !
remote:  !     If you are trying to deploy a Node.js application, ensure that this
remote:  !     file is present at the top level directory. This directory has the
remote:  !     following files:
remote:  !
remote:  !     gallery-links.txt
remote:  !     index.html
remote:  !     Open Source/
remote:  !     React Native Projects/
remote:  !     README.md
remote:  !     style.css
remote:  !
remote:  !     If you are trying to deploy an application written in another
remote:  !     language, you need to change the list of buildpacks set on your
remote:  !     Heroku app using the 'heroku buildpacks' command.
remote:  !
remote:  !     For more information, refer to the following documentation:
remote:  !     https://devcenter.heroku.com/articles/buildpacks
remote:  !     https://devcenter.heroku.com/articles/nodejs-support#activation
remote:
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to floating-wave-76653.
remote:
To https://git.heroku.com/floating-wave-76653.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/floating-wave-76653.git'


```
I already have a package.json file in the root directory and have previously pushed to heroku but for some reason it shows this error.

**Comment by mars** [comment] 2018-12-06 19:43
Hi @Shivendra30 😄

Two things I see from your log:

1. Your app's buildpack is `heroku/nodejs` not this one `mars/create-react-app`, where you filed this issue. To set your app to use this buildpack, execute:

    ```bash
    heroku buildpacks:set mars/create-react-app
    ```
2. If the build process is throwing an error that `package.json` is missing, then it must be missing! The error shows what files are at the root level, and sure enough there is no `package.json`.  Please make sure `package.json` is committed at the top-level (root) of the git repo. If it's in a sub-directory, it will not be found.

**Comment by walexzzy** [comment] 2019-02-21 23:12
![image](https://user-images.githubusercontent.com/28973041/53208265-bd452700-35fb-11e9-933f-8b8cea1578d8.png)

This is the error am facing please help

**Comment by mars** [comment] 2019-02-22 00:53
@walexzzy looks like you're trying to deploy a Python app? That topic is not related to this repo. Try the [Heroku documentation for deploying Python](https://devcenter.heroku.com/articles/python-support), or search the web for: `python "app not compatible with buildpack"`

**Comment by kcn21** [comment] 2019-04-12 07:12
Hi @mars
I'm getting following error with buildpacks 
please Help

remote: -----> App not compatible with buildpack: https://github.com/kcn21/EducationPortal.git
remote:        bash: /app/tmp/buildpacks/92a497ca9abb293376466dcfb1444191a5b2cdd4d86cd4a3bfced038be2aaea4c4352b4dcdfa8fe62264c8cb027dfab6466aa5e7ff243cb8f4c9d7fc2f5434bc/bin/detect: No such file or directory
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to education-portal21.
remote:
To https://git.heroku.com/education-portal21.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/education-portal21.git'

**Comment by kcn21** [comment] 2019-04-12 07:27
I already have a package.json file in the root directory and have previously pushed to heroku but for some reason it shows this error.

**Comment by mars** [comment] 2019-05-02 18:07
@kcn21 looks like the buildpack https://github.com/kcn21/EducationPortal.git is causing that error, not this mars/create-react-app buildpack.

If that's not supposed to be a buildpack, then reset it to use this one (if you do intend to use this one):

```
heroku buildpacks:clear
heroku buildpacks:set mars/create-react-app
```

**Comment by kcn21** [comment] 2019-05-04 18:33
I want to use this buildpack  https://github.com/kcn21/EducationPortal.git for my app to deploy on heroku

**Comment by mars** [comment] 2019-05-04 19:35
@kcn this is issues for mars/create-react-app-buildpack. Please check [Heroku’s Buildpack API documentation](https://devcenter.heroku.com/articles/buildpack-api) for how to make your buildpack’s `bin/detect` script work.

**Comment by mars** [comment] 2019-05-04 19:47
@kcn actually I think you’re confused about what a “buildpack” is. That EducationPortal.git you linked to is the source code for an Angular.js app, not a buildpack.

**Comment by splnlss** [comment] 2019-06-04 17:29
I have my server and client folders in one repo. How can I deploy to heroku when my package.json is in
respective subfolders rather than the root?

**Comment by mars** [comment] 2019-06-04 18:14
@splnlss In general, Heroku's build system expects one app per repo, and so I do not advise trying to use a monorepo unless you're up for blazing your own trail (such as with the [monorepo buildpack](https://elements.heroku.com/buildpacks/lstoll/heroku-buildpack-monorepo) or [Terraform](https://www.terraform.io/docs/providers/heroku/r/build.html)).

In your case if server & client are both JavaScript, then you could follow the pattern exemplified in [create-react-app + Node server](https://github.com/mars/heroku-cra-node).

**Comment by zhnedyalkow** [comment] 2019-11-07 09:03
Hi @mars,

I have received following error during the deploy:

Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 1.08 KiB | 1.08 MiB/s, done.
Total 3 (delta 0), reused 3 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/mars/create-react-app.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to e-commerce-crawn.
remote: 
To https://git.heroku.com/e-commerce-crawn.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/e-commerce-crawn.git'
zhitomir@zhitomir-HP-ProBook-4530s:~/Desktop/Junior to Senior/React course/React-Andrei-course/e-commerce$ ls
node_modules  package.json  package-lock.json  public  react.txt  README.md  src
zhitomir@zhitomir-HP-ProBook-4530s:~/Desktop/Junior to Senior/React course/React-Andrei-course/e-commerce$ cd src
zhitomir@zhitomir-HP-ProBook-4530s:~/Desktop/Junior to Senior/React course/React-Andrei-course/e-commerce/src$ git push heroku master 
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 1.08 KiB | 1.08 MiB/s, done.
Total 3 (delta 0), reused 3 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/mars/create-react-app.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to e-commerce-crawn.
remote: 
To https://git.heroku.com/e-commerce-crawn.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/e-commerce-crawn.git'

The command is executed in following directory which contains:
node_modules  package.json  package-lock.json  public  react.txt  README.md  src

git push heroku master

git remote -v -->
heroku  https://git.heroku.com/e-commerce-crawn.git (fetch)
heroku  https://git.heroku.com/e-commerce-crawn.git (push)
origin  git@github.com:zhnedyalkow/e-commerce.git (fetch)
origin  git@github.com:zhnedyalkow/e-commerce.git (push)

Tried:
heroku buildpacks:clear
heroku buildpacks:set mars/create-react-app

And removed yarn.lock:

git rm yarn.lock
git commit . -m 'Remove Yarn'

Thank you in advance!

**Comment by mars** [comment] 2019-11-07 14:23
@zhnedyalkow please read the responses to the issue, because your app is going to have a similar resolution as everyone else here.

The error means that the React app must be at the root of your repo; its `package.json` must be present at the top-level, but Heroku didn’t find it.

**Comment by mars** [comment] 2019-11-07 15:45
One of the typical mistakes that can make is look like `package.json` is missing, is if your deploying a branch other than master and master doesn’t have that file.

You can deploy a branch from command line with:

```
git push heroku other-branch:master
```

…replacing `other-branch` with the branch name to deploy.

**Comment by Daniel9756** [comment] 2019-11-28 22:45
mars please help me. This error have delayed me for months now. I can push my app to Heroku. I have tried all that I could.

$ git push heroku master
Enumerating objects: 1204, done.
Counting objects: 100% (1204/1204), done.
Delta compression using up to 2 threads
Compressing objects: 100% (1185/1185), done.
Writing objects: 100% (1204/1204), 2.72 MiB | 1.08 MiB/s, done.
Total 1204 (delta 414), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/mars/create-react-app.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to blooming-mountain-92243.
remote:
To https://git.heroku.com/blooming-mountain-92243.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/blooming-mountain-92243.git'

**Comment by Daniel9756** [comment] 2019-11-28 22:46
mars please help me. This error have delayed me for months now. I can,t push my app to Heroku. I have tried all that I could.

$ git push heroku master
Enumerating objects: 1204, done.
Counting objects: 100% (1204/1204), done.
Delta compression using up to 2 threads
Compressing objects: 100% (1185/1185), done.
Writing objects: 100% (1204/1204), 2.72 MiB | 1.08 MiB/s, done.
Total 1204 (delta 414), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/mars/create-react-app.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to blooming-mountain-92243.
remote:
To https://git.heroku.com/blooming-mountain-92243.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/blooming-mountain-92243.git'

**Comment by mars** [comment] 2019-11-29 17:19
@Daniel9756 pretty much everything that can cause this error is already discussed in this thread:

Root cause is that `package.json` is not at the top level of the source code being deployed.

Make sure you’re deploying the intended branch.

Make sure your app is really using this buildpack.

Make sure that `package.json` is not in a sub-directory.

**Comment by mars** [comment] 2019-11-29 20:38
(Cleaned-up unrelated comments that are misleading.)
