### ISSUE TITLE
Served build not minified

### ISSUE THREAD

**Issue by StevePavlin** [mars/create-react-app-buildpack#48] opened 2017-05-05 10:41 UTC
Hi,

When I run git push heroku master with the buildpack, I can see that the build is created. When I view my index.html file on my production website, I see it non minified with one js file inserted (/static/js/bundle.js).

This is my static.json

```
{
  "root": "build/",
  "https_only": true,
  "routes": {
    "/**": "index.html"
  },
  "headers": {
    "/": {
      "Cache-Control": "no-store, no-cache"
    },
    "**.js": {
      "Cache-Control": "public, max-age=31536000"
    },
    "**.css": {
      "Cache-Control": "public, max-age=31536000"
    }
  }
}
```

I see this when inspecting index.html in production:

```
<div id="root"></div>
<script type="text/javascript" src="/static/js/bundle.js"></script></body>
```

Any idea why this is happening? It seems weird because the build/ directory is the one that should be served, but it seems like its serving something else. Is there something I'm missing?

**Comment by mars** [comment] 2017-05-05 14:09
I just performed a [test deployment](https://cra-mini-check.herokuapp.com) of a freshly generated app using the most recent create-react-app, version 1.3.0. The result is minified as expected:

```html
<script type="text/javascript" src="/static/js/main.ff2f771d.js"></script>
```

What does your `package.json` contain? Do you have any other dotfiles or custom config?

**Comment by StevePavlin** [comment] 2017-05-06 20:12
```
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "dev": "dev.bat && npm start",
    "deploy-staging": "git add . && git commit --allow-empty -m \"Heroku\" && git push staging master",
    "deploy-production": "git add . && git commit --allow-empty -m \"Heroku\" && git push production master"
  },
```

I'm running the deploy-staging and deploy-production scripts when deploying.

**Comment by mars** [comment] 2017-05-06 20:44
Nothing you just posted seems to indicate what's causing `index.html` to reference an unminified bundle.

What else is in `package.json`?

Is the `/build` directory committed? (It shouldn't be.)

Does the committed `index.html` contain this incorrect `<script>` tag? (It should not be committed; `npm run build` inserts it.)

Does running `npm run build` locally produce the same results?

Maybe check the create-react-app issues?

I cannot help anymore without seeing the code to reproduce it myself.

**Comment by mars** [comment] 2017-05-12 15:41
Closing because I cannot reproduce and no response from @StevePavlin

**Closed as completed by mars** 2017-05-12 15:41 UTC

**Comment by StevePavlin** [comment] 2017-05-13 06:29
Hey, apologize for the late response, forgot to check this.

For anyone else who is having this problem, the issue is that the /build directory was being committed. Make sure to delete it before using this buildpack!
